# github action to buld and deploy the thunderpay server to azure

name: Deploy Server

on:
  workflow_dispatch:

env:
  AZURE_SERVER_APP_NAME: "thunder-pay"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Install dependencies
        run: dotnet restore ./src/ThunderPay.Server/ThunderPay.Server.csproj

      - name: Build
        run: dotnet build ./src/ThunderPay.Server/ThunderPay.Server.csproj

      - name: Publish
        run: dotnet publish ./src/ThunderPay.Server/ThunderPay.Server.csproj --configuration Release --output ./publish

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_SERVER_APP_NAME }}
          publish-profile: ${{ secrets.SERVER_PUBLISH_PROFILE }}
          package: ./publish
